product:
  brand: ESPHome
  description: DLMS Meter Austria
description: |
  Requires an ESPHome node running the `dlms_meter` component (e.g., from `github://SimonFischer04/esphome@dlms-meter`),
  configured for Austrian DLMS meters.

render:
  - usage: grid
    default: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2
    advanced: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2
      timeout: 10s # optional
