product:
  brand: ESPHome
  description: DLMS Meter Austria
description: |
  Benötigt ein ESPHome Gerät mit der `dlms_meter` Komponente (z.B. von `github://SimonFischer04/esphome@dlms-meter`),
  konfiguriert für österreichische DLMS-Zähler.

render:
  - usage: grid
    default: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2 # IP-Adresse oder Hostname
    advanced: |
      type: template
      template: esphome-dlms-austria
      usage: grid
      host: 192.0.2.2 # IP-Adresse oder Hostname
      timeout: 10s # Zeitüberschreitung, optional
